### ISSUE TITLE
Stacked Chart example not rendering properly according to data

### ISSUE THREAD

**Issue by cher7369** [Esri/ember-cli-cedar#88]
https://esri.github.io/ember-cli-cedar/#/charts/bar-stacked

On this example, the values form the example service, do not seem to be rendering correctly. I would expect to see the following values based on queries to the service:

Jordan > 
"query": {
        "where": "City='Jordan'",
        "orderByFields": "Number_of_SUM DESC",
        "groupByFieldsForStatistics": "Type",
        "outStatistics": [{
          "statisticType": "sum",
          "onStatisticField": "Number_of",
          "outStatisticFieldName": "Number_of_SUM"
        }]
      }

Results >>
High School > 13
Middle School > 6
Elementary School > 1
** Showing Correctly

Dewitt > 
"name": "Dewitt",
      "query": {
        "where": "City='Dewitt'",
        "orderByFields": "Number_of_SUM DESC",
        "groupByFieldsForStatistics": "Type",
        "outStatistics": [{
          "statisticType": "sum",
          "onStatisticField": "Number_of",
          "outStatisticFieldName": "Number_of_SUM"
        }]
      }

Results >>
Elementary School > 1
** Showing values in High School that are note returned

Fayetteville >
"query": {
        "where": "City='Fayetteville'",
        "orderByFields": "Number_of_SUM DESC",
        "groupByFieldsForStatistics": "Type",
        "outStatistics": [{
          "statisticType": "sum",
          "onStatisticField": "Number_of",
          "outStatisticFieldName": "Number_of_SUM"
        }]
      }

Results >>
High School > 8
Middle School > 0
Elementary School > 1
** No values showing for High School or Middle School (looks like Dewitt took on these values instead)

It seems like the Dewitt category is taking on the values for the Fayetteville category since the query did not return anything for these stacked categories.

Does this chart require all categories shown to have values for all of the categories within the stacked bars in order to show correctly?

**Comment by tomwayson** [comment]
Good catch @cher7369!

We _just_ fixed this bug in cedar https://github.com/Esri/cedar/pull/411 and will be cutting a release w/ that today, and then updating ember-cli-cedar. I will ping you when that is done.

**Comment by cher7369** [comment]
Great thanks Tom!
